import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from "./theme-provider";
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: 'Landing Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-zinc-100 dark:bg-zinc-800 duration-1000">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
